feat(init): create new module for deploying bitbucket runner autoscaler to kubernetes
lablabs/terraform-aws-eks-bitbucket-runner-autoscaler pull request #1
Opened 2024-10-16 17:00 UTC by katapultcloud

# Description

## Type of change

- [ ] A bug fix (PR prefix `fix`)
- [x] A new feature (PR prefix `feat`)
- [ ] A code change that neither fixes a bug nor adds a feature (PR prefix `refactor`)
- [ ] Adding missing tests or correcting existing tests (PR prefix `test`)
- [ ] Changes that do not affect the meaning of the code like white-spaces, formatting, missing semi-colons, etc. (PR prefix `style`)
- [ ] Changes to our CI configuration files and scripts (PR prefix `ci`)
- [ ] Documentation only changes (PR prefix `docs`)

## How Has This Been Tested?
Tested on development edge environment.

2024-10-21 10:55 UTC, jaygridley requested changes

2024-10-21 10:55 UTC, jaygridley commented on main.tf
> + * [![Terraform validate](https://github.com/lablabs/terraform-aws-eks-bitbucket-runner-autoscaler/actions/workflows/validate.yaml/badge.svg)](https://github.com/lablabs/terraform-aws-eks-bitbucket-r
I would keep these banners at the top.

2024-10-21 10:55 UTC, jaygridley commented on iam.tf
> +resource "aws_iam_role_policy_attachment" "ecr" {
I would keep this in the LARA integration only. Community might not care about ECR at all.

2024-10-21 10:55 UTC, jaygridley commented on iam.tf
> +locals {
I am considering creating a "clone" of `universal-addon/addon-irsa` module for the OIDC approach. It can have support for the same stuff as the IRSA module does and, in addition, create an OIDC provider. What do you think?

2024-10-21 10:55 UTC, jaygridley commented on main.tf
> + * ## Cross-Account IAM Access for Runners
I would add these specifics into `examples/basic/README.md`

2024-10-23 14:04 UTC, katapultcloud commented on iam.tf
> +locals {
I have put all oidc resources into a module. Take a look, I like it this way it seems cleaner. Maybe we can incorporate the oidc in the universal addon codebase too since it's generic enough.

2024-10-24 08:48 UTC, jaygridley requested changes

2024-10-24 08:48 UTC, jaygridley commented on modules/addon-oidc/iam.tf
I would make this module to be part of universal-addon a use it from there.

2024-10-24 08:48 UTC, jaygridley commented on modules/addon-oidc/iam.tf
> +resource "aws_iam_openid_connect_provider" "this" {
I am thinking of making this resource optional, enabled by default, but have a way how to pass a custom OpenID provider. Does it seems reasonable?

2024-10-24 11:47 UTC, katapultcloud commented on modules/addon-oidc/iam.tf
> +resource "aws_iam_openid_connect_provider" "this" {
sounds good I've added a switch for this by passing a custom provider arn

2024-10-24 11:48 UTC, katapultcloud commented on modules/addon-oidc/iam.tf
ok when you're happy with this here I'll open a PR to universal addon repo, and change the module source url here

2024-10-24 20:08 UTC, jaygridley requested changes

2024-10-24 20:08 UTC, jaygridley commented on variables-addon.tf
> +  default     = "bitbucket-runner-autoscaler"
These defaults should not be here, but in main.tf, otherwise this will be overridden when universal repo is synced.

2024-10-24 20:08 UTC, jaygridley commented on variables-addon.tf
> +  default     = "bitbucket-runner-autoscaler"
These defaults should not be here, but in main.tf, otherwise this will be overridden when universal repo is synced.

2024-10-24 20:08 UTC, jaygridley commented on main.tf
> + * [![Terraform validate](https://github.com/lablabs/terraform-aws-eks-bitbucket-runner-autoscaler/actions/workflows/validate.yaml/badge.svg)](https://github.com/lablabs/terraform-aws-eks-bitbucket-r
But after module description to keep a common format.

2024-10-25 15:15 UTC, jaygridley approved these changes
LGTM

2024-10-25 15:17 UTC, merged